name: ğŸ›°ï¸ Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: [nesprex-mapper] ğŸ› ï¸ Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: [nesprex-mapper] ğŸ“¦ Restore dependencies
      working-directory: './backend/nesprex-mapper'
      run: dotnet restore
    - name: [nesprex-mapper] ğŸ—ï¸ Build
      working-directory: './backend/nesprex-mapper'
      run: dotnet build --no-restore
    - name: [nesprex-mapper] ğŸ§ª Test
      working-directory: './backend/nesprex-mapper'
      run: dotnet test --no-build --verbosity normal
